from .flores import FLORESDataModule, FLORESDataset
from .bmlama import BMLAMADataModule, BMLAMADataset

FLORES_LANGUAGES = FLORESDataModule.SUPPORTED_LANGUAGES
BMLAMA_LANGUAGES_17 = BMLAMADataModule.SUPPORTED_LANGUAGES_17
BMLAMA_LANGUAGES_53 = BMLAMADataModule.SUPPORTED_LANGUAGES_53
